name: Code quality verification

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # required for usage with pull requests

      - name: Install dependencies
        run: npm ci

      - name: Format files using prettier
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit possible changes
        with:
          commit_message: "style: format files using prettier"

      - name: Run linters
        run: npm run check
