name: Code quality verification

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # required for usage with pull requests

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run check

      - name: Run build
        run: npm run build
