name: Code quality verification

on:
  pull_request:
    types:
      - "opened"
      - "synchronize"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # required for usage with pull requests

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      # Linters need to run after the build, because the build is generating the SvelteKit tsconfig.json.
      - name: Run linters
        run: npm run check

  schema-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # required for usage with pull requests

      - name: Validate bundeslaender.json against schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "src/data/bundeslaender.json"
          schema: "src/schema/bundeslaender.schema.json"

      - name: Validate cna.json against schema
        uses: cardinalby/schema-validator-action@v1
        with:
          file: "src/data/cna.json"
          schema: "src/schema/cna.schema.json"
